---
title: "peakcall_step2"
output: 
  html_document:
    df_print: paged
  html_notebook:
editor_options:
  chunk_output_type: inline
--- 
 
```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(Signac); library(Seurat)

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
samples=list()
samples[["limb"]]=c(1,2);samples[["nasal"]]=c(3,4);samples[["somite"]]=c(5,6)
sample.name <- c("L21","L24","N15","N18","S12","S15")
data.name <- c("10x_atac_12012021","10x_atac_10042020","10x_atac_12012021","10x_atac_10042020","10x_atac_12012021","10x_atac_12012021")
anno_path <- "/scicore/home/tschoppp/GROUP/references/genomes/ENS_g6/chicken_Gg6_atac_pre/"
meta_path <- paste0("~/scATAC/integration/",paste0(names(samples),"_atac_integrated010721_meta.rds"))
rds_path <- paste0("~/scATAC/integration/",paste0(names(samples),"_atac_integrated010721.rds"))

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## consensus peakset for each embryonic origin
for(i in 1:length(samples)){
  ## read in meta file
  tmp.samples=names(samples)[i]
  hm.integrated=readRDS(meta_path[i])
  hm.integrated$dataset=as.character(hm.integrated$dataset)
  hm.integrated$fine=as.character(hm.integrated$fine)
  
  ## fixed to 501 bp
  pk=list(); extendSummits=250
  for(m in unique(hm.integrated$fine)){
    cls=m
    nrpeaks=read.table(paste0("~/scATAC/peakcall/",tmp.samples,"/",tmp.samples,"_cls",cls,".peak_summits.bed"), header = F,sep = "\t",stringsAsFactors = F)
    regions=paste0(nrpeaks$V1,":",nrpeaks$V2,"-",nrpeaks$V3)
    #out <- GRanges(out$V1, IRanges(out$V2 + 1, out$V3), score = out$V5)
    gr=NULL;gr=StringToGRanges(regions,sep=c(":","-"))
    gr=resize(gr, extendSummits * 2 + 1, "center")
    gr$peak_called_in=cls
    gr$score=nrpeaks$V5 #It's calculated as int(-10*log10qvalue).
    pk[[cls]]=gr
  }
  
  ## remove redundant peaks
  # https://rdrr.io/github/GreenleafLab/ArchR/man/nonOverlappingGR.html
  unionPeaks <- pk$sub_1
  glist=unique(hm.integrated$fine)
  for(i in glist[!(glist %in% "sub_1")]){
    unionPeaks=c(unionPeaks,pk[[i]])
    unionPeaks <- nonOverlappingGR(unionPeaks, by = "score", decreasing = TRUE)
  };length(unionPeaks)
  
  ## Not Overlapping Blacklist!
  # there is no chicken blacklist, so we treat top 0.1% most accessible bins as blacklist.
  my.atac=readRDS(rds_path[i])
  DefaultAssay(my.atac)="bins"
  my.atac <- FindTopFeatures(my.atac, min.cutoff = 'q99.9')
  blacklist=StringToGRanges(VariableFeatures(my.atac),sep=c(":","-")); length(blacklist)
  unionPeaks=subsetByOverlaps(unionPeaks,blacklist,invert = TRUE)
  
  # save
  saveRDS(unionPeaks,paste0("~/scATAC/peakcall/",tmp.samples,"/nonredundantpeaks_",tmp.samples,".rds"))
}

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## consensus peakset for all 3 origins

# read in peakset
rm(pk); pk=list()
for(i in 1:length(samples)){
  tmp.samples=names(samples)[i]
  pk[[i]]=readRDS(paste0("~/scATAC/peakcall/nonredundantpeaks_",tmp.samples,".rds"))
  pk[[i]]$peak_called_in=tmp.samples
}

# remove redundant peaks
unionPeaks <- pk$somite
glist=unique(samples)
for(i in glist[!(glist %in% "somite")]){
  unionPeaks=c(unionPeaks,pk[[i]])
  unionPeaks <- nonOverlappingGR(unionPeaks, by = "score", decreasing = TRUE)
}

# only keep autosomes and chrZ
remainPeaks=keepSeqlevels(unionPeaks,c(1:28,30:33,"Z"),pruning.mode="coarse"); length(remainPeaks)

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## plot
mtx.stat=data.frame(peak_cls=peaks$peak_called_in,
               origin="overall")
mtx.stat$peak_cls=factor(mtx.stat$peak_cls,levels = c("nasal","somite","limb"))
ocol=c("#DC0078","#008FD4","#FFD01F")
names=c("nasal","somite","limb")
g = ggplot(mtx.stat,aes(origin)) + theme_classic()
g1=g + geom_bar(aes(fill = peak_cls))  +
  scale_fill_manual("legend", values = ocol) +
  theme(legend.text = element_text(size=15)) +
  ylab("peak") + xlab("origin")
g1

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## save
saveRDS(remainPeaks,paste0("~/scATAC/peakcall/nonredundantpeaks_combined.rds"))

```

## log

```{r, message=FALSE, warning=FALSE, echo=TRUE}
sessionInfo()
```

