---
title: "scATAC_convergence_preprocess"
output: 
  html_document:
    df_print: paged
  html_notebook:
editor_options:
  chunk_output_type: inline
--- 

to get highly variable peaks

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(Signac); library(Seurat)
library(GenomeInfoDb); library(ensembldb)
library(GenomicRanges); library(future)
library(BSgenome.Ggallus.ensembl.galGal6); library(TFBSTools)
library(scran)

set.seed(1234)
```

## split into 6 samples

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#need to run on terminal: srun --nodes=1 --cpus-per-task=4 --mem=96G --pty bash
my.samplenames = c("L21", "L24",  "N15", "N18", "S12", "S15")
my.files=paste0("~/scATAC/integration/",c("limb_atac_integrated010721.rds","nasal_atac_integrated010721.rds","somite_atac_integrated010721.rds"))
my.metas=paste0("~/scATAC/integration/",c("limb_atac_integrated010721_meta.rds","nasal_atac_integrated010721_meta.rds","somite_atac_integrated010721_meta.rds"))

#split into 3 origin * 2 stage = 6 samples
my.samples = list()
for (i in 1:length(my.files)) {
  my.tmp = readRDS(my.files[i])
  my.tmp[["bins"]]=NULL
  my.tmp[["peaks"]]=NULL
  my.tmp[["activity"]]=NULL
  my.tmp[["activity_combat"]]=NULL
  my.tmp[["activity.name"]]=NULL
  my.tmp[["chromvar"]]=NULL
  
  meta.tmp=readRDS(my.metas[i])
  my.tmp=AddMetaData(my.tmp,metadata = meta.tmp[rownames(my.tmp@meta.data),c("broad","annotation_broad","fine","annotation_fine")])
  if(i==1){
    my.tmp@meta.data$origin="limb"
  }else if(i==2){
    my.tmp@meta.data$origin="nasal"
  }else if(i==3){
    my.tmp@meta.data$origin="somite"
  }
  my.split = SplitObject(my.tmp, split.by = "dataset" )
  my.samples = do.call(c, list(my.samples, my.split))
  rm(my.tmp)
}
names(my.samples)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
saveRDS(my.samples,"~/scATAC/preprocessed_scatac_6samples_onlyM2P.rds")
```

## normalization with scran

```{r, message=FALSE, warning=FALSE, echo=TRUE}
my.samples=readRDS("~/scATAC/preprocessed_scatac_6samples_onlyM2P.rds")
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
hvgs=NULL
#make separate Seurat object
#changed a bit compared to scRNA: computeSumFactors() min.mean=0.1-->0.05
#getTopHVGs() n=2000-->20000

for (i in 1:length(my.samples)) {
  DefaultAssay(my.samples[[i]])="macs2peaks"
  Idents(my.samples[[i]])=my.samples[[i]]$broad
  #scran: get sizeFactors
  sce=as.SingleCellExperiment(my.samples[[i]],assay="macs2peaks")
  myclusters=my.samples[[i]]@meta.data$broad
  sce = computeSumFactors(sce, clusters=myclusters, min.mean=0.05) #https://github.com/theislab/scib/blob/master/notebooks/data_preprocessing/pancreas/02_normalize_human_pancreas.ipynb
  my.samples[[i]]=AddMetaData(my.samples[[i]],metadata = sizeFactors(sce),col.name = "size_factor")
  #get hvgs
  #https://github.com/satijalab/seurat/issues/747
  #sce <- logNormCounts(sce)
  dec <- modelGeneVar(sce, assay.type = "logcounts")
  hvgs=c(hvgs,getTopHVGs(dec, n=2000))
  
}
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
saveRDS(my.samples,"~/scATAC/preprocessed_scatac_6samples_onlyM2P.rds")
```

## get highly variable peaks

remove the ones from chrW.

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#rank hvgs by times of appearance, keep the top 2000
hvgsum=as.data.frame(table(hvgs));dim(hvgsum)
hvgsum=hvgsum[order(-hvgsum$Freq),]
#remove W chromosme peaks
hvgsum=hvgsum[!grepl("^W-",hvgsum$hvgs),];dim(hvgsum)

write.table(hvgsum,"~/scATAC/integration/preprocessed_scranHVPs.txt",quote=F)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
hvgs.seurat=NULL
for (i in 1:length(my.samples)) {
  DefaultAssay(my.samples[[i]])="macs2peaks"
  my.samples[[i]] <- NormalizeData(my.samples[[i]], verbose = FALSE)
  my.samples[[i]] <- FindVariableFeatures(my.samples[[i]], selection.method = "vst", 
                                          nfeatures = 20000, verbose = FALSE)
  
  hvgs.seurat=c(hvgs.seurat,VariableFeatures(my.samples[[i]]))
}

hvgsum=as.data.frame(table(hvgs.seurat));dim(hvgsum)
hvgsum=hvgsum[order(-hvgsum$Freq),]
#remove W chromosme peaks
hvgsum=hvgsum[!grepl("^W-",hvgsum$hvgs),];dim(hvgsum)

write.table(hvgsum,"~/scATAC/integration/preprocessed_seuratHVPs.txt",quote=F)
```

## log

```{r, message=FALSE, warning=FALSE, echo=TRUE}
sessionInfo()
```

