---
title: "scATAC_binarization"
output: 
  html_document:
    df_print: paged
  html_notebook:
editor_options:
  chunk_output_type: inline
---

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(Seurat)
library(pheatmap)
library("viridis");library(ggplot2)
library(dplyr); library(scales)

source("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/colors/limbcolors.R")
source("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/colors/nasalcolors.R")
source("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/colors/somitecolors.R")
my.cols = c(limb.colors(3),nasal.colors(3), somite.colors(3))

my.origins=c("limb","nasal","somite")
my.samplenames = c("L21", "L24", "N15", "N18", "S12", "S15")

```

### binarized 

```{r, message=FALSE, warning=FALSE, echo=TRUE}
combined=readRDS("~/scATAC/integration/convergence_integrated_signac_onlyM2P_HvpDaps_combined.rds")

hvgsum1=read.table("~/scATAC/integration/preprocessed_scranHVPs.txt")
hvgsum1=hvgsum1[hvgsum1$Freq>=2,];length(hvgsum1$hvgs)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
tmp=GetAssayData(combined,slot = "counts")
tmp[tmp>=1]=1
combined[['binarized']]=CreateAssayObject(data=tmp)
combined@assays$binarized@counts=tmp
combined@active.assay="binarized"
VariableFeatures(combined)=hvgsum1$hvgs
combined <- RunSVD(combined)
combined <- RunUMAP(combined, reduction = "lsi", dims = 2:30)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE,fig.width=12,fig.height=8}
p1=DimPlot(combined,group.by = "origin")
p2=DimPlot(combined,group.by = "dataset")
p1+p2

DimPlot(combined,group.by = "annotation_broad")
DimPlot(combined,group.by = "annotation_fine")
```

## log

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
sessionInfo()
```
