---
title: "figure5_heatmap"
output: 
  html_document:
    df_print: paged
  html_notebook:
editor_options:
  chunk_output_type: inline
---

for panel A-C

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
# packages
library(ggplot2); library(patchwork); library(gridExtra)
#library(ArchR); packageVersion("ArchR")
library(ComplexHeatmap);library(circlize)
library(RColorBrewer); library(dplyr)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
# download from archR github
.ArchRHeatmap <- function(
  mat = NULL, 
  scale = FALSE,
  limits = c(min(mat), max(mat)),
  colData = NULL, 
  color = paletteContinuous(set = "solarExtra", n = 100),
  clusterCols = TRUE,
  clusterRows = FALSE,
  labelCols = FALSE,
  labelRows = FALSE,
  colorMap = NULL,
  useRaster = TRUE,
  rasterQuality = 5,
  split = NULL,
  fontSizeRows = 10,
  fontSizeCols = 10,
  fontSizeLabels = 8,
  colAnnoPerRow = 4,
  showRowDendrogram = FALSE,
  showColDendrogram = FALSE,
  customRowLabel = NULL,
  customRowLabelIDs = NULL,
  customColLabel = NULL,
  customColLabelIDs = NULL,
  customLabelWidth = 0.75,
  rasterDevice = "png",
  padding = 45,
  borderColor = NA,
  draw = TRUE,
  name = "Heatmap"
  ){
  
  #Packages
  #.requirePackage("ComplexHeatmap", source = "bioc")
  #.requirePackage("circlize", source = "cran")
  
  #Z-score
  if (scale) {
    message("Scaling Matrix..")
    mat <- .rowZscores(mat, limit = FALSE)
    name <- paste0(name," Z-Scores")
  }
  
  #Get A Color map if null
  if (is.null(colorMap)) {
    colorMap <- .colorMapAnno(colData)
  }
  
  #Prepare ColorMap format for Complex Heatmap
  if (!is.null(colData)){
    colData = data.frame(colData)
    colorMap <- .colorMapForCH(colorMap, colData) #change
    showLegend <- .checkShowLegend(colorMap[match(names(colorMap), colnames(colData))]) #change
  }else {
    colorMap <- NULL
    showLegend <- NULL
  }
  
  #Prepare Limits if needed
  breaks <- NULL
  if (!is.null(limits)) {
    mat[mat > max(limits)] <- max(limits)
    mat[mat < min(limits)] <- min(limits)
  }else{
    limits <- c(round(min(mat),2), round(max(mat),2))
  }

  #Scale Values 0 - 1
  mat <- (mat - min(limits)) / (max(limits) - min(limits))
  breaks <- seq(0, 1, length.out = length(color))
  color <- circlize::colorRamp2(breaks, color)

  if(exists('anno_mark', where='package:ComplexHeatmap', mode='function')){
    anno_check_version_rows <- ComplexHeatmap::anno_mark
    anno_check_version_cols <- ComplexHeatmap::anno_mark
  }else{
    anno_check_version_rows <- ComplexHeatmap::row_anno_link
    anno_check_version_cols <- ComplexHeatmap::column_anno_link
  }

  #Annotation Heatmap
  if(!is.null(colData) & !is.null(customColLabel)){
    message("Adding Annotations..")
    if(is.null(customColLabelIDs)){
      customColLabelIDs <- colnames(mat)[customColLabel]
    }
    ht1Anno <- HeatmapAnnotation(
      df = colData,
      col = colorMap, 
      show_legend = showLegend,
      show_annotation_name = TRUE,
      gp = gpar(col = "NA"),
      annotation_legend_param =
        list(
          nrow = min(colAnnoPerRow, max(round(nrow(colData)/colAnnoPerRow), 1))
        ),
      foo = anno_check_version_cols(at = customColLabel, labels = customColLabelIDs, labels_gp = gpar(fontsize = fontSizeLabels))
    )

  }else if(!is.null(colData)){
    message("Adding Annotations..")
    ht1Anno <- HeatmapAnnotation(
      df = colData,
      col = colorMap, 
      show_legend = showLegend,
      show_annotation_name = TRUE,
      gp = gpar(col = "NA"),
      annotation_legend_param =
        list(
          nrow = min(colAnnoPerRow, max(round(nrow(colData)/colAnnoPerRow), 1))
        )
    )
  }else if(is.null(colData) & !is.null(customColLabel)){
    if(is.null(customColLabelIDs)){
      customColLabelIDs <- colnames(mat)[customColLabel]
    }
    message("Adding Annotations..")
    #print(customColLabel)
    #print(customColLabelIDs)
    #ht1Anno <- columnAnnotation(foo = anno_check_version_cols(
    #   at = customColLabel, labels = customColLabelIDs),
    #   width = unit(customLabelWidth, "cm") + max_text_width(customColLabelIDs))
    #ht1Anno <- HeatmapAnnotation(foo = anno_mark(at = c(1:4, 20, 60, 1097:1100), labels = month.name[1:10]))
    ht1Anno <- HeatmapAnnotation(foo = anno_check_version_cols(at = customColLabel, labels = customColLabelIDs, labels_gp = gpar(fontsize = fontSizeLabels)))
  }else{
    ht1Anno <- NULL
  }

  message("Preparing Main Heatmap..")
  ht1 <- Heatmap(
    
    #Main Stuff
    matrix = as.matrix(mat),
    name = name,
    col = color, 
    
    #Heatmap Legend
    heatmap_legend_param = 
      list(
           at = c(0, 1),
           labels = c(round(min(limits),2), round(max(limits),2)),
           color_bar = "continuous", 
           legend_direction = "horizontal",
           legend_width = unit(3, "cm")
      ), 
    rect_gp = gpar(col = borderColor), 
    
    #Column Options
    show_column_names = labelCols,
    cluster_columns = clusterCols, 
    show_column_dend = showColDendrogram,
    clustering_method_columns = "ward.D2",
    column_names_gp = gpar(fontsize = fontSizeCols), 
    column_names_max_height = unit(100, "mm"),
    
    #Row Options
    show_row_names = labelRows,
    row_names_gp = gpar(fontsize = fontSizeRows), 
    cluster_rows = clusterRows, 
    show_row_dend = showRowDendrogram, 
    clustering_method_rows = "ward.D2",
    split = split, 
    
    #Annotation
    top_annotation = ht1Anno, 

    #Raster Info
    use_raster = useRaster, 
    raster_device = rasterDevice, 
    raster_quality = rasterQuality
  )

  if(!is.null(customRowLabel)){
    if(is.null(customRowLabelIDs)){
      customRowLabelIDs <- rownames(mat)[customRowLabel]
    }
    ht1 <- ht1 + rowAnnotation(link = 
        anno_check_version_rows(at = customRowLabel, labels = customRowLabelIDs, labels_gp = gpar(fontsize = fontSizeLabels)),
        width = unit(customLabelWidth, "cm") + max_text_width(customRowLabelIDs))
  }

  if(draw){
    draw(ht1, 
      padding = unit(c(padding, padding, padding, padding), "mm"), 
      heatmap_legend_side = "bot", 
      annotation_legend_side = "bot")
  }else{
    ht1
  }

}

.colorMapAnno <- function(colData = NULL, customAnno = NULL, discreteSet = "stallion", continuousSet = "solarExtra"){
  discreteCols <- sapply(colData,function(x) !is.numeric(x))
  if(!is.null(customAnno)){
    colorMap <- lapply(seq_along(discreteCols),function(x){
      if(discreteCols[x]){
        colors <- paletteDiscrete(values = colData[[names(discreteCols[x])]], set = discreteSet)
        names(colors) <- unique(colData[[names(discreteCols[x])]])
        attr(colors, "discrete") <- TRUE
      }else{
        colors <- paletteContinuous(set = continuousSet)
        attr(colors, "discrete") <- FALSE
      }
      if(length(which(customAnno[,1] %in% names(discreteCols[x]))) > 0){
        if(length(which(customAnno[,2] %in% names(colors))) > 0){
          customAnnox <- customAnno[which(customAnno[,2] %in% names(colors)),]
          colors[which(names(colors) %in% customAnnox[,2])] <- paste0(customAnnox[match(names(colors),customAnnox[,2]),3])
        }
      }
      return(colors)
    })
    names(colorMap) <- colnames(colData)
    return(colorMap)
  }else{
    colorMap <- lapply(seq_along(discreteCols), function(x){
      if(discreteCols[x]){
       colors <- paletteDiscrete(values = colData[[names(discreteCols[x])]], set = discreteSet)
       names(colors) <- unique(colData[[names(discreteCols[x])]])
       attr(colors, "discrete") <- TRUE
      }else{
       colors <- paletteContinuous(set = continuousSet)
       attr(colors, "discrete") <- FALSE
      }
      return(colors)
    })
    names(colorMap) <- colnames(colData)
    return(colorMap)
  }

}

.colorMapForCH <- function(colorMap = NULL, colData = NULL){
  colorMap <- colorMap[which(names(colorMap) %in% colnames(colData))]
  colorMapCH <- lapply(seq_along(colorMap), function(x){
    if(attr(colorMap[[x]],"discrete")){
      colorx <- colorMap[[x]]
    }else{
      vals <- colData[[names(colorMap)[x]]][!is.na(colData[[names(colorMap)[x]]])]
      s <-  seq(min(vals), max(vals), length.out = length(colorMap[[x]]))
      colorx <- circlize::colorRamp2(s, colorMap[[x]])
    }
    if(any(is.na(names(colorx)))){
      names(colorx)[is.na(names(colorx))] <- paste0("NA",seq_along(names(colorx)[is.na(names(colorx))]))
    }
    return(colorx)
  })
  names(colorMapCH) <- names(colorMap)
  return(colorMapCH)
}

.checkShowLegend <- function(colorMap = NULL, max_discrete = 30){
  show <- lapply(seq_along(colorMap), function(x){
      if(attr(colorMap[[x]],"discrete") && length(unique(colorMap[[x]])) > max_discrete){
        sl <- FALSE
      }else{
        sl <- TRUE
      }
      return(sl)
    }) %>% unlist
  names(show) <- names(colorMap)
  return(show)
}
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
my.origins=c("limb","somite","nasal")

cls.retain=list()
cls.retain[["nasal"]]=c("neuralcrestDerivedMesenchyme","eyeConnectiveTissue","chondrocytes")
cls.retain[["somite"]]=c("somite2","somite1","chondrocytes")
cls.retain[["limb"]]=c("WNT5AMesenchyme","amb_mesenchymeORnsConnectiveTissue","chondrocytes","lateChondrocytes")

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

## nasal

```{r, message=FALSE, warning=FALSE, echo=TRUE}
origin="nasal"

my.cols=c("#FC89AC",
                        "#B0445C","#FFC0CB",
                        "#65000B","#DC0078")
names(my.cols)=c('mesenchymeActiveCell',
                'amb_periocularMesenchyme','neuralcrestDerivedMesenchyme', 
                   'eyeConnectiveTissue','chondrocytes')

#proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/",origin,"_mesenchyme_p2glinks_ArchR"))

```

### plot

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## reduce the number of rows and columns to show
# k.used=c(length(cls.retain[[origin]]),(length(cls.retain[[origin]])+2),10,20)
k.select=length(cls.retain[[origin]])

# reduce the number of rows
# top N & add a bar plot to show the number of p2g links per k cluster
peak.cls=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLink_scatacPeakCluster_k",k.select,"_",origin,".txt"),sep = "\t");table(peak.cls$hkmeans)
peak.cls=peak.cls[order(peak.cls$hkmeans,-peak.cls$Correlation),]
peak.cls$p2gID=rownames(peak.cls)
peak.cls.top=as.data.frame(peak.cls) %>%
  group_by(hkmeans) %>%
  top_n(n = 40, wt = Correlation) 
table(peak.cls.top$hkmeans)
# the genes with more mesenchymal p2gLinks can be key regulators 
table(peak.cls$gene)[order(-table(peak.cls$gene))][1:50]


knn.meta=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_knnMeta_",origin,".txt"),sep = "\t")
rownames(knn.meta)=knn.meta$knnID

# reduce the number of columns
knn.select=knn.meta
knn.select$groupBy=factor(knn.select$groupBy,levels = cls.retain[[origin]])
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]
knn.select=knn.select[(knn.select$groupBy %in% cls.retain[[origin]]) & (knn.select$percent.retain>0.5),]

# order by celltype & average pseudotime
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]

p1=readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_heatmapMatrix_",origin,".rds"))
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#change the order of hkmeans
peak.cls$hkmeans.str=""
peak.cls[peak.cls$hkmeans==1,"hkmeans.str"]="k3"
peak.cls[peak.cls$hkmeans==2,"hkmeans.str"]="k2"
peak.cls[peak.cls$hkmeans==3,"hkmeans.str"]="k1"

peak.cls.top$hkmeans.str=""
peak.cls.top[peak.cls.top$hkmeans==1,"hkmeans.str"]="k3"
peak.cls.top[peak.cls.top$hkmeans==2,"hkmeans.str"]="k2"
peak.cls.top[peak.cls.top$hkmeans==3,"hkmeans.str"]="k1"

peak.cls.top$hkmeans.str=factor(peak.cls.top$hkmeans.str,levels=c("k1","k2","k3"))
peak.cls.top=peak.cls.top[order(peak.cls.top$hkmeans.str),]

peak.cls$hkmeans.str=factor(peak.cls$hkmeans.str,levels=rev(c("k1","k2","k3")))

p=list();n=1
for(i in unique(peak.cls$hkmeans.str)){
  p[[n]]=ggplot(peak.cls[peak.cls$hkmeans.str==i,]) +
    aes(x = hkmeans.str) + ggtitle("frequency") +
    geom_bar(fill="gray") + theme_classic() + ylim(c(0,max(table(peak.cls$hkmeans.str))+200))
  n=n+1
}
print(p[[1]]+p[[2]]+p[[3]])

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_hkmeansFreq_",origin,"_v2.pdf"),width = 6,height = 4)
print(p[[1]]+p[[2]]+p[[3]])
dev.off()

```

```{r, message=FALSE, warning=FALSE, echo=TRUE,fig.height=6,fig.width=12}
## replot the heatmap
#cD <- DataFrame(row.names=knn.select$knnID, groupBy = knn.select$groupby)
cD <- data.frame(groupBy = knn.select$groupBy)
rownames(cD)=knn.select$knnID

palGroup = my.cols[names(my.cols) %in% cls.retain[[origin]]]
colorMap <- list(groupBy = palGroup)
attr(colorMap[[1]], "discrete") <- TRUE

mATAC=p1@listData$ATAC$matrix
limitsATAC = c(-2, 2); #palATAC = paletteContinuous("solarExtra")
col.atac.raw=brewer.pal(n = 9, name ="YlOrBr")
palATAC = colorRampPalette(col.atac.raw[c(1,2,4,8,9)])(256)
htATAC <- .ArchRHeatmap(
  mat = mATAC[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsATAC,
  color = palATAC, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("ATAC Z-Scores\n", nrow(mATAC), " P2GLinks")
)

mRNA=p1@listData$RNA$matrix
limitsRNA = c(-2, 2); #palRNA = paletteContinuous("blueYellow")
palRNA = colorRampPalette(c("white","grey80","black"))(256)
htRNA <- .ArchRHeatmap(
  mat = mRNA[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsRNA,
  color = palRNA, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("RNA Z-Scores\n", nrow(mRNA), " P2GLinks")
)

htATAC + htRNA

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_topHeatmap_k",k.select,"_",origin,".pdf"),width = 8,height = 6)
htATAC + htRNA
dev.off()
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

## somite

```{r, message=FALSE, warning=FALSE, echo=TRUE}
origin="somite"

my.cols=c("#00CCFF","#00416A","#8BD6FF","#008FD4")
names(my.cols)=c('somite1', 'chondrocytes',
                      'somite2', 'amb_somite')

#proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/",origin,"_mesenchyme_p2glinks_ArchR"))

```

### plot

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## reduce the number of rows and columns to show
# k.used=c(length(cls.retain[[origin]]),(length(cls.retain[[origin]])+2),10,20)
k.select=length(cls.retain[[origin]])

# reduce the number of rows
# top N & add a bar plot to show the number of p2g links per k cluster
peak.cls=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLink_scatacPeakCluster_k",k.select,"_",origin,".txt"),sep = "\t");table(peak.cls$hkmeans)
peak.cls=peak.cls[order(peak.cls$hkmeans,-peak.cls$Correlation),]
peak.cls$p2gID=rownames(peak.cls)
peak.cls.top=as.data.frame(peak.cls) %>%
  group_by(hkmeans) %>%
  top_n(n = 40, wt = Correlation) 
table(peak.cls.top$hkmeans)

knn.meta=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_knnMeta_",origin,".txt"),sep = "\t")
rownames(knn.meta)=knn.meta$knnID

# reduce the number of columns
knn.select=knn.meta
knn.select$groupBy=factor(knn.select$groupBy,levels = cls.retain[[origin]])
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]
knn.select=knn.select[(knn.select$groupBy %in% cls.retain[[origin]]) & (knn.select$percent.retain>0.5),]

# order by celltype & average pseudotime
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]

p1=readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_heatmapMatrix_",origin,".rds"))
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#change the order of hkmeans
peak.cls$hkmeans.str=""
peak.cls[peak.cls$hkmeans==1,"hkmeans.str"]="k1"
peak.cls[peak.cls$hkmeans==2,"hkmeans.str"]="k2"
peak.cls[peak.cls$hkmeans==3,"hkmeans.str"]="k3"

peak.cls.top$hkmeans.str=""
peak.cls.top[peak.cls.top$hkmeans==1,"hkmeans.str"]="k1"
peak.cls.top[peak.cls.top$hkmeans==2,"hkmeans.str"]="k2"
peak.cls.top[peak.cls.top$hkmeans==3,"hkmeans.str"]="k3"

peak.cls.top$hkmeans.str=factor(peak.cls.top$hkmeans.str,levels=c("k1","k2","k3"))
peak.cls.top=peak.cls.top[order(peak.cls.top$hkmeans.str),]

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_hkmeansFreq_",origin,".pdf"),width = 3,height = 6)
peak.cls$hkmeans.str=factor(peak.cls$hkmeans.str,levels=rev(c("k1","k2","k3")))
p0=ggplot(peak.cls) +
  aes(x = hkmeans.str) + ggtitle("frequency of each hkmeans cluster") +
  geom_bar(fill="gray") + theme_classic() +coord_flip() 
print(p0)
dev.off()

p=list();n=1
for(i in unique(peak.cls$hkmeans.str)){
  p[[n]]=ggplot(peak.cls[peak.cls$hkmeans.str==i,]) +
    aes(x = hkmeans.str) + ggtitle("frequency") +
    geom_bar(fill="gray") + theme_classic() + ylim(c(0,max(table(peak.cls$hkmeans.str))+200))
  n=n+1
}
print(p[[1]]+p[[2]]+p[[3]])

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_hkmeansFreq_",origin,"_v2.pdf"),width = 6,height = 4)
print(p[[1]]+p[[2]]+p[[3]])
dev.off()

```

```{r, message=FALSE, warning=FALSE, echo=TRUE,fig.height=15,fig.width=12}
## replot the heatmap
#cD <- DataFrame(row.names=knn.select$knnID, groupBy = knn.select$groupby)
cD <- data.frame(groupBy = knn.select$groupBy)
rownames(cD)=knn.select$knnID

palGroup = my.cols[names(my.cols) %in% cls.retain[[origin]]]
colorMap <- list(groupBy = palGroup)
attr(colorMap[[1]], "discrete") <- TRUE

mATAC=p1@listData$ATAC$matrix
limitsATAC = c(-2, 2); #palATAC = paletteContinuous("solarExtra")
col.atac.raw=brewer.pal(n = 9, name ="YlOrBr")
palATAC = colorRampPalette(col.atac.raw[c(1,2,4,8,9)])(256)
htATAC <- .ArchRHeatmap(
  mat = mATAC[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsATAC,
  color = palATAC, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("ATAC Z-Scores\n", nrow(mATAC), " P2GLinks")
)

mRNA=p1@listData$RNA$matrix
limitsRNA = c(-2, 2); #palRNA = paletteContinuous("blueYellow")
palRNA = colorRampPalette(c("white","grey80","black"))(256)
htRNA <- .ArchRHeatmap(
  mat = mRNA[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsRNA,
  color = palRNA, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("RNA Z-Scores\n", nrow(mRNA), " P2GLinks")
)

htATAC + htRNA

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_topHeatmap_k",k.select,"_",origin,".pdf"),width = 8,height = 6)
htATAC + htRNA
dev.off()
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

## limb

```{r, message=FALSE, warning=FALSE, echo=TRUE}
origin="limb"

my.cols=c("#FFE78A","#FFB817",
          "#662D0B","#FFD01F",
          "#FFA309","#C49606",
          "#88540B")
names(my.cols)=c('WNT5AMesenchyme', 'anteriorMesenchyme',
                      'mesenchymeORnsConnectiveTissue', 'chondrocytes',
                      'lateChondrocytes', 'SHOX2Mesenchyme',
                      'amb_mesenchymeORnsConnectiveTissue')

#proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/",origin,"_mesenchyme_p2glinks_ArchR"))

```

### plot

```{r, message=FALSE, warning=FALSE, echo=TRUE}
## reduce the number of rows and columns to show
# k.used=c(length(cls.retain[[origin]]),(length(cls.retain[[origin]])+2),10,20)
k.select=length(cls.retain[[origin]])

# reduce the number of rows
# top N & add a bar plot to show the number of p2g links per k cluster
peak.cls=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLink_scatacPeakCluster_k",k.select,"_",origin,".txt"),sep = "\t");table(peak.cls$hkmeans)
peak.cls=peak.cls[order(peak.cls$hkmeans,-peak.cls$Correlation),]
peak.cls$p2gID=rownames(peak.cls)
peak.cls.top=as.data.frame(peak.cls) %>%
  group_by(hkmeans) %>%
  top_n(n = 40, wt = Correlation) 
table(peak.cls.top$hkmeans)

knn.meta=read.table(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_knnMeta_",origin,".txt"),sep = "\t")
rownames(knn.meta)=knn.meta$knnID

# reduce the number of columns
knn.select=knn.meta
knn.select$groupBy=factor(knn.select$groupBy,levels = cls.retain[[origin]])
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]
knn.select=knn.select[(knn.select$groupBy %in% cls.retain[[origin]]) & (knn.select$percent.retain>0.5),]

# order by celltype & average pseudotime
knn.select=knn.select[order(knn.select$groupBy,knn.select$average.ptime),]

p1=readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/scATAC/peak2gene/p2gLinks_heatmapMatrix_",origin,".rds"))
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#change the order of hkmeans
peak.cls$hkmeans.str=""
peak.cls[peak.cls$hkmeans==1,"hkmeans.str"]="k1"
peak.cls[peak.cls$hkmeans==2,"hkmeans.str"]="k4"
peak.cls[peak.cls$hkmeans==3,"hkmeans.str"]="k3"
peak.cls[peak.cls$hkmeans==4,"hkmeans.str"]="k2"

peak.cls.top$hkmeans.str=""
peak.cls.top[peak.cls.top$hkmeans==1,"hkmeans.str"]="k1"
peak.cls.top[peak.cls.top$hkmeans==2,"hkmeans.str"]="k4"
peak.cls.top[peak.cls.top$hkmeans==3,"hkmeans.str"]="k3"
peak.cls.top[peak.cls.top$hkmeans==4,"hkmeans.str"]="k2"

peak.cls.top$hkmeans.str=factor(peak.cls.top$hkmeans.str,levels=c("k1","k2","k3","k4"))
peak.cls.top=peak.cls.top[order(peak.cls.top$hkmeans.str),]

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_hkmeansFreq_",origin,".pdf"),width = 3,height = 6)
peak.cls$hkmeans.str=factor(peak.cls$hkmeans.str,levels=rev(c("k1","k2","k3","k4")))
p0=ggplot(peak.cls) +
  aes(x = hkmeans.str) + ggtitle("frequency of each hkmeans cluster") +
  geom_bar(fill="gray") + theme_classic() +coord_flip() 
print(p0)
dev.off()

p=list();n=1
for(i in unique(peak.cls$hkmeans.str)){
  p[[n]]=ggplot(peak.cls[peak.cls$hkmeans.str==i,]) +
    aes(x = hkmeans.str) + ggtitle("frequency") +
    geom_bar(fill="gray") + theme_classic() + ylim(c(0,max(table(peak.cls$hkmeans.str))+200))
  n=n+1
}
print(p[[1]]+p[[2]]+p[[3]]+p[[4]])

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_hkmeansFreq_",origin,"_v2.pdf"),width = 4,height = 8)
print(p[[1]]+p[[2]]+p[[3]]+p[[4]])
dev.off()
```

```{r, message=FALSE, warning=FALSE, echo=TRUE,fig.height=15,fig.width=12}
## replot the heatmap
#cD <- DataFrame(row.names=knn.select$knnID, groupBy = knn.select$groupby)
cD <- data.frame(groupBy = knn.select$groupBy)
rownames(cD)=knn.select$knnID

palGroup = my.cols[names(my.cols) %in% cls.retain[[origin]]]
colorMap <- list(groupBy = palGroup)
attr(colorMap[[1]], "discrete") <- TRUE

mATAC=p1@listData$ATAC$matrix
limitsATAC = c(-2, 2); #palATAC = paletteContinuous("solarExtra")
col.atac.raw=brewer.pal(n = 9, name ="YlOrBr")
palATAC = colorRampPalette(col.atac.raw[c(1,2,4,8,9)])(256)
htATAC <- .ArchRHeatmap(
  mat = mATAC[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsATAC,
  color = palATAC, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("ATAC Z-Scores\n", nrow(mATAC), " P2GLinks")
)

mRNA=p1@listData$RNA$matrix
limitsRNA = c(-2, 2); #palRNA = paletteContinuous("blueYellow")
palRNA = colorRampPalette(c("white","grey80","black"))(256)
htRNA <- .ArchRHeatmap(
  mat = mRNA[peak.cls.top$p2gID,knn.select$knnID],
  scale = FALSE,
  limits = limitsRNA,
  color = palRNA, 
  colData = cD,
  colorMap = colorMap,
  clusterCols = FALSE,
  clusterRows = FALSE,
  split = peak.cls.top$hkmeans.str,
  labelRows = FALSE,
  labelCols = FALSE,
  draw = FALSE,
  name = paste0("RNA Z-Scores\n", nrow(mRNA), " P2GLinks")
)

htATAC + htRNA

pdf(paste0("/scicore/home/tschoppp/GROUP/lab/skeletalconvergence/fromMenghan/figure_drafts/fig5/p2gLinks_topHeatmap_k",k.select,"_",origin,".pdf"),width = 8,height = 6)
htATAC + htRNA
dev.off()
```

## log

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
sessionInfo()
```

