---
title: "p2gLinks"
output: 
  html_document:
    df_print: paged
  html_notebook:
editor_options:
  chunk_output_type: inline
---

run ArchR peak2gene analysis (add batch correction by harmony & replace by signac dimension)

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(ArchR)
library(Signac);library(Seurat)
library(FNN); library(matrixStats); library(limma)

```

## limb

```{r, message=FALSE, warning=FALSE, echo=TRUE}
samples="limb"
sample.name <- c("L21","L24")

#################
## read in ArchR project & signac project
proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/integration/",samples))

my.atac=readRDS("~/scATAC/integration/limb_atac_integrated010721.rds")
my.meta=readRDS("/scicore/home/tschoppp/wang0007/scATAC/integration/limb_atac_integrated010721_meta.rds")
my.atac=AddMetaData(my.atac,metadata = my.meta[rownames(my.atac@meta.data),c("broad","annotation_broad","fine","annotation_fine")],col.name = c("broad","annotation_broad","fine","annotation_fine"))
nrow(my.meta)

#################
## add peak matrix
peaks <- readRDS(paste0("/scicore/home/tschoppp/wang0007/scATAC/peakcall/nonredundantpeaks_combined.rds"))
npGr=keepSeqlevels(peaks,c(1:28,30:33),pruning.mode="coarse"); table(seqnames(npGr))
addArchRChrPrefix(chrPrefix = FALSE); getArchRChrPrefix()
proj <- addPeakSet(proj, peakSet = npGr, force = TRUE)
proj <- addPeakMatrix(proj)

#################
## add annotation
cellnames = rownames(my.meta)
cellnmod = gsub("_","#",cellnames); cellnmod = gsub("L21","l21",cellnmod)
meta.atac=my.meta; rownames(meta.atac)=cellnmod
proj$annotation=meta.atac[proj$cellNames,"annotation_fine"]

#################
## add harmony dimensions
proj <- addIterativeLSI(ArchRProj = proj, useMatrix = "TileMatrix", name = "IterativeLSI",force = TRUE)
proj <- addHarmony(ArchRProj = proj, reducedDims = "IterativeLSI", name = "Harmony", groupBy = "Sample")

#use the harmony from signac project, as it better correct batch effect
df=my.atac@reductions$harmony@cell.embeddings
rownames(df)=gsub("L21_","l21#",rownames(df))
rownames(df)=gsub("L24_","L24#",rownames(df))
cnames=colnames(proj@reducedDims$Harmony$matDR)
proj@reducedDims$Harmony$matDR=as.matrix(df[proj$cellNames,1:30])
colnames(proj@reducedDims$Harmony$matDR)=cnames

#run umap
proj <- addUMAP(ArchRProj = proj, reducedDims = "Harmony", dimsToUse =2:30,name = "UMAPHarmony", force = TRUE)

#################
## integrate with scRNA
mtx.fl_rna = readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/Chris.shared/for.Menghan/forelimb_seurat_290420.rds")) #"forelimb_seurat_290420.rds","frontonasal_seurat_290420.rds","somites_seurat_290420.rds"
meta.rna=readRDS("~/scRNA/clustering/meta_limb.rds")
mtx.fl_rna=AddMetaData(mtx.fl_rna,metadata = meta.rna[rownames(mtx.fl_rna@meta.data),])

#change scRNA from geneID to geneName
exp=GetAssayData(mtx.fl_rna,assay = "RNA",slot = "counts")
exp=exp[rownames(exp) %in% rownames(gene.info),];dim(exp)
rownames(exp)=gene.info[rownames(exp),"genename"]
mtx.fl_rna[['RNA_geneName']] = CreateAssayObject(counts=exp)

#subset
mtx.fl_rna$dataset=mtx.fl_rna$orig.ident
mtx.fl_rna$annotation=mtx.fl_rna$annotation_fine
scrna.1=subset(mtx.fl_rna,cells=rownames(mtx.fl_rna@meta.data[mtx.fl_rna@meta.data$dataset %in% sample.name,])) # & grepl("sub_",mtx.fl_rna@meta.data$fine)
table(scrna.1$annotation_fine)

se.1 <- SummarizedExperiment(assays = GetAssayData(scrna.1,assay="RNA_geneName"), 
                             colData = scrna.1@meta.data)

#################
## addGeneIntegrationMatrix with harmony dimension
dims="Harmony"
proj <- addGeneIntegrationMatrix(proj, seRNA=se.1, useMatrix = "GeneScoreMatrix",
                                 matrixName = "GeneIntegrationMatrix", reducedDims = dims, dimsToUse = 2:30,
                                 groupRNA = "annotation", groupATAC = "annotation",
                                 groupList = NULL,
                                 sampleCellsATAC = length(proj$cellNames),sampleCellsRNA = length(se.1$annotation),
                                 plotUMAP = FALSE, useImputation = FALSE,
                                 addToArrow = FALSE, force = TRUE)

#################
## calculate p2g links
proj <- addPeak2GeneLinks(
  ArchRProj = proj,seed=1234,
  useMatrix = "GeneIntegrationMatrix",
  reducedDims = dims,
  dimsToUse = 2:30
)

#################
## save
p2g=NULL
p2g <- getPeak2GeneLinks(
  ArchRProj = proj,
  corCutOff = 0.45,FDRCutOff = 0.05,
  resolution = 1,
  returnLoops = FALSE
)
p2g$geneName <- mcols(metadata(p2g)$geneSet)$name[p2g$idxRNA]
p2g$peakName <- (metadata(p2g)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2g$idxATAC]
dim(p2g)

p2geneDF=NULL
p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
p2geneDF$geneName <- mcols(metadata(p2geneDF)$geneSet)$name[p2geneDF$idxRNA]
p2geneDF$peakName <- (metadata(p2geneDF)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2geneDF$idxATAC]

p=list()
p[["archr"]]=p2g
p[["full"]]=p2geneDF

saveRDS(p,paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/limb_allcelltype_p2glinks_ArchR.rds"))
saveArchRProject(ArchRProj = proj, outputDirectory = paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/limb_allcelltype_p2glinks_ArchR"), load = FALSE)

```

## nasal

```{r, message=FALSE, warning=FALSE, echo=TRUE}
samples="nasal"
sample.name <- c("N15","N18")

#################
## read in ArchR project & signac project
proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/integration/",samples))

my.atac=readRDS("~/scATAC/integration/nasal_atac_integrated010721.rds")
my.meta=readRDS("/scicore/home/tschoppp/wang0007/scATAC/integration/nasal_atac_integrated010721_meta.rds")
my.atac=AddMetaData(my.atac,metadata = my.meta[rownames(my.atac@meta.data),c("broad","annotation_broad","fine","annotation_fine")],col.name = c("broad","annotation_broad","fine","annotation_fine"))
nrow(my.meta)

#################
## add peak matrix
peaks <- readRDS(paste0("/scicore/home/tschoppp/wang0007/scATAC/peakcall/nonredundantpeaks_combined.rds"))
npGr=keepSeqlevels(peaks,c(1:28,30:33),pruning.mode="coarse"); table(seqnames(npGr))
addArchRChrPrefix(chrPrefix = FALSE); getArchRChrPrefix()
proj <- addPeakSet(proj, peakSet = npGr, force = TRUE)
proj <- addPeakMatrix(proj)

#################
## add annotation
cellnames = rownames(my.meta)
cellnmod = gsub("_","#",cellnames)
meta.atac=my.meta; rownames(meta.atac)=cellnmod
proj$annotation=meta.atac[proj$cellNames,"annotation_fine"]

#################
## add harmony dimensions
proj <- addIterativeLSI(ArchRProj = proj, useMatrix = "TileMatrix", name = "IterativeLSI",force = TRUE)
proj <- addHarmony(ArchRProj = proj, reducedDims = "IterativeLSI", name = "Harmony", groupBy = "Sample")

#use the harmony from signac project, as it better correct batch effect
df=my.atac@reductions$harmony@cell.embeddings
rownames(df)=gsub("N15_","N15#",rownames(df))
rownames(df)=gsub("N18_","N18#",rownames(df))
cnames=colnames(proj@reducedDims$Harmony$matDR)
proj@reducedDims$Harmony$matDR=as.matrix(df[proj$cellNames,1:30])
colnames(proj@reducedDims$Harmony$matDR)=cnames

#run umap
proj <- addUMAP(ArchRProj = proj, reducedDims = "Harmony", dimsToUse =2:30,name = "UMAPHarmony", force = TRUE)

#################
## integrate with scRNA
mtx.fl_rna = readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/Chris.shared/for.Menghan/frontonasal_seurat_290420.rds")) #"forelimb_seurat_290420.rds","frontonasal_seurat_290420.rds","somites_seurat_290420.rds"
meta.rna=readRDS("~/scRNA/clustering/meta_nasal.rds")
mtx.fl_rna=AddMetaData(mtx.fl_rna,metadata = meta.rna[rownames(mtx.fl_rna@meta.data),])

#change scRNA from geneID to geneName
exp=GetAssayData(mtx.fl_rna,assay = "RNA",slot = "counts")
exp=exp[rownames(exp) %in% rownames(gene.info),];dim(exp)
rownames(exp)=gene.info[rownames(exp),"genename"]
mtx.fl_rna[['RNA_geneName']] = CreateAssayObject(counts=exp)

#subset
mtx.fl_rna$dataset=mtx.fl_rna$orig.ident
mtx.fl_rna$annotation=mtx.fl_rna$annotation_fine
scrna.1=subset(mtx.fl_rna,cells=rownames(mtx.fl_rna@meta.data[mtx.fl_rna@meta.data$dataset %in% sample.name,])) # & grepl("sub_",mtx.fl_rna@meta.data$fine)
table(scrna.1$annotation_fine)

se.1 <- SummarizedExperiment(assays = GetAssayData(scrna.1,assay="RNA_geneName"), 
                             colData = scrna.1@meta.data)

#################
## addGeneIntegrationMatrix with harmony dimension
dims="Harmony"
proj <- addGeneIntegrationMatrix(proj, seRNA=se.1, useMatrix = "GeneScoreMatrix",
                                 matrixName = "GeneIntegrationMatrix", reducedDims = dims, dimsToUse = 2:30,
                                 groupRNA = "annotation", groupATAC = "annotation",
                                 groupList = NULL,
                                 sampleCellsATAC = length(proj$cellNames),sampleCellsRNA = length(se.1$annotation),
                                 plotUMAP = FALSE, useImputation = FALSE,
                                 addToArrow = FALSE, force = TRUE)

#################
## calculate p2g links
proj <- addPeak2GeneLinks(
  ArchRProj = proj,seed=1234,
  useMatrix = "GeneIntegrationMatrix",
  reducedDims = dims,
  dimsToUse = 2:30
)

#################
## save
p2g=NULL
p2g <- getPeak2GeneLinks(
  ArchRProj = proj,
  corCutOff = 0.45,FDRCutOff = 0.05,
  resolution = 1,
  returnLoops = FALSE
)
p2g$geneName <- mcols(metadata(p2g)$geneSet)$name[p2g$idxRNA]
p2g$peakName <- (metadata(p2g)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2g$idxATAC]
dim(p2g)

p2geneDF=NULL
p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
p2geneDF$geneName <- mcols(metadata(p2geneDF)$geneSet)$name[p2geneDF$idxRNA]
p2geneDF$peakName <- (metadata(p2geneDF)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2geneDF$idxATAC]

p=list()
p[["archr"]]=p2g
p[["full"]]=p2geneDF

saveRDS(p,paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/nasal_allcelltype_p2glinks_ArchR.rds"))
saveArchRProject(ArchRProj = proj, outputDirectory = paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/nasal_allcelltype_p2glinks_ArchR"), load = FALSE)

```

## somite

```{r, message=FALSE, warning=FALSE, echo=TRUE}
samples="somite"
sample.name <- c("S12","S15")

#################
## read in ArchR project & signac project
proj <- loadArchRProject(path=paste0("/scicore/home/tschoppp/wang0007/scATAC/integration/",samples))

my.atac=readRDS("~/scATAC/integration/somite_atac_integrated010721.rds")
my.meta=readRDS("/scicore/home/tschoppp/wang0007/scATAC/integration/somite_atac_integrated010721_meta.rds")
my.atac=AddMetaData(my.atac,metadata = my.meta[rownames(my.atac@meta.data),c("broad","annotation_broad","fine","annotation_fine")],col.name = c("broad","annotation_broad","fine","annotation_fine"))
nrow(my.meta)

#################
## add peak matrix
peaks <- readRDS(paste0("/scicore/home/tschoppp/wang0007/scATAC/peakcall/nonredundantpeaks_combined.rds"))
npGr=keepSeqlevels(peaks,c(1:28,30:33),pruning.mode="coarse"); table(seqnames(npGr))
addArchRChrPrefix(chrPrefix = FALSE); getArchRChrPrefix()
proj <- addPeakSet(proj, peakSet = npGr, force = TRUE)
proj <- addPeakMatrix(proj)

#################
## add annotation
cellnames = rownames(my.meta)
cellnmod = gsub("_","#",cellnames)
meta.atac=my.meta; rownames(meta.atac)=cellnmod
proj$annotation=meta.atac[proj$cellNames,"annotation_fine"]

#################
## add harmony dimensions
proj <- addIterativeLSI(ArchRProj = proj, useMatrix = "TileMatrix", name = "IterativeLSI",force = TRUE)
proj <- addHarmony(ArchRProj = proj, reducedDims = "IterativeLSI", name = "Harmony", groupBy = "Sample")

#use the harmony from signac project, as it better correct batch effect
df=my.atac@reductions$harmony@cell.embeddings
rownames(df)=gsub("S12_","S12#",rownames(df))
rownames(df)=gsub("S15_","S15#",rownames(df))
cnames=colnames(proj@reducedDims$Harmony$matDR)
proj@reducedDims$Harmony$matDR=as.matrix(df[proj$cellNames,1:30])
colnames(proj@reducedDims$Harmony$matDR)=cnames

#run umap
proj <- addUMAP(ArchRProj = proj, reducedDims = "Harmony", dimsToUse =2:30,name = "UMAPHarmony", force = TRUE)

#################
## integrate with scRNA
mtx.fl_rna = readRDS(paste0("/scicore/home/tschoppp/GROUP/lab/Chris.shared/for.Menghan/somites_seurat_290420.rds")) #"forelimb_seurat_290420.rds","frontonasal_seurat_290420.rds","somites_seurat_290420.rds"
meta.rna=readRDS("~/scRNA/clustering/meta_somite.rds")
mtx.fl_rna=AddMetaData(mtx.fl_rna,metadata = meta.rna[rownames(mtx.fl_rna@meta.data),])

#change scRNA from geneID to geneName
exp=GetAssayData(mtx.fl_rna,assay = "RNA",slot = "counts")
exp=exp[rownames(exp) %in% rownames(gene.info),];dim(exp)
rownames(exp)=gene.info[rownames(exp),"genename"]
mtx.fl_rna[['RNA_geneName']] = CreateAssayObject(counts=exp)

#subset
mtx.fl_rna$dataset=mtx.fl_rna$orig.ident
mtx.fl_rna$annotation=mtx.fl_rna$annotation_fine
scrna.1=subset(mtx.fl_rna,cells=rownames(mtx.fl_rna@meta.data[mtx.fl_rna@meta.data$dataset %in% sample.name,])) # & grepl("sub_",mtx.fl_rna@meta.data$fine)
table(scrna.1$annotation_fine)

se.1 <- SummarizedExperiment(assays = GetAssayData(scrna.1,assay="RNA_geneName"), 
                             colData = scrna.1@meta.data)

#################
## addGeneIntegrationMatrix with harmony dimension
dims="Harmony"
proj <- addGeneIntegrationMatrix(proj, seRNA=se.1, useMatrix = "GeneScoreMatrix",
                                 matrixName = "GeneIntegrationMatrix", reducedDims = dims, dimsToUse = 2:30,
                                 groupRNA = "annotation", groupATAC = "annotation",
                                 groupList = NULL,
                                 sampleCellsATAC = length(proj$cellNames),sampleCellsRNA = length(se.1$annotation),
                                 plotUMAP = FALSE, useImputation = FALSE,
                                 addToArrow = FALSE, force = TRUE)

#################
## calculate p2g links
proj <- addPeak2GeneLinks(
  ArchRProj = proj,seed=1234,
  useMatrix = "GeneIntegrationMatrix",
  reducedDims = dims,
  dimsToUse = 2:30
)

#################
## save
p2g=NULL
p2g <- getPeak2GeneLinks(
  ArchRProj = proj,
  corCutOff = 0.45,FDRCutOff = 0.05,
  resolution = 1,
  returnLoops = FALSE
)
p2g$geneName <- mcols(metadata(p2g)$geneSet)$name[p2g$idxRNA]
p2g$peakName <- (metadata(p2g)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2g$idxATAC]
dim(p2g)

p2geneDF=NULL
p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
p2geneDF$geneName <- mcols(metadata(p2geneDF)$geneSet)$name[p2geneDF$idxRNA]
p2geneDF$peakName <- (metadata(p2geneDF)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2geneDF$idxATAC]

p=list()
p[["archr"]]=p2g
p[["full"]]=p2geneDF

saveRDS(p,paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/somite_allcelltype_p2glinks_ArchR.rds"))
saveArchRProject(ArchRProj = proj, outputDirectory = paste0("/scicore/home/tschoppp/wang0007/scATAC/identifyRE/somite_allcelltype_p2glinks_ArchR"), load = FALSE)

```

## log

```{r, message=FALSE, warning=FALSE, echo=TRUE}

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
sessionInfo()
```

